import { App } from "./modules/app.js"

let data = [
    {
        question: "What is the name of the artist who painted ‘Mona Lisa’?",
        answer: "Leonardo Da Vinv"
    },
    {
        question: "Where is Lincoln Memorial situated in America?",
        answer: "Washington D.C."
    },
    {
        question: "What is the capital of Brazil?",
        answer: "Brasilia"
    },

    {
        question: "How can you be sure the numbers are really random?",
        answer: "Oddly enough, it is theoretically impossible to prove that a random number generator is really random. Rather, you analyse an increasing amount of numbers produced by a given generator, and depending on the results, your confidence in the generator increases (or decreases, as the case may be). This is explained in more detail on my Statistical Analysis page, which also contains two studies of the numbers generated by RANDOM.ORG, both of which concluded that the numbers are sound. In addition, the continually updated Real-Time Statistics page gives you an indication of the quality of the numbers produced over time."
    }
]

const app = new App("FAQ", data)
document.title = "FAQ"
document.body.appendChild(app.render())